POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
    "name":"t",
    "email":"t@a.com",
    "password": "111411"
    
}

###login sin conexion a BDD

POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
  "name": "prueba2",
  "email": "rp2@hm.com",
  "password": "1234567"
}

### users
GET http://127.0.0.1:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3MzE3NzcxMDYsImV4cCI6MTczMTk5MzEwNn0.XyaLC9WFZVin1eOnj2_1Qhhp6ry_hJEyF6i-rd1PMFM