POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
    "name":"t",
    "email":"t@a.com",
    "password": "111411"
    
}

###login sin conexion a BDD

POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
  "name": "prueba2",
  "email": "rp2@hm.com",
  "password": "1234567"
}

### users
GET http://127.0.0.1:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3MzE3NzQ3NDksImV4cCI6MTczMTc3NDgwOX0.m-tEYEmLNVHYE9S4-zrtAenAz9-f7vTZ3bEhq3Lp890